name: Auto Restart Codespace

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  restart_codespace:
    runs-on: ubuntu-latest

    steps:
      
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh jq

     
      - name: Authenticate GitHub CLI with Personal Classic Token
        run: |
          echo "${{ secrets.PERSONAL_CLASSIC_TOKEN }}" | gh auth login --with-token

     
      - name: Check Codespace Status
        run: |
          CODESPACE_NAME="supreme-umbrella-4jg59rpq4v49h5rwr"
          STATUS=$(gh codespace list --json name,state | jq -r --arg name "$CODESPACE_NAME" '.[] | select(.name == $name) | .state')

          echo "Codespace status: $STATUS"

          if [ "$STATUS" == "Shutdown" ]; then
            echo "Codespace is offline. Starting it..."
            gh codespace ssh -c $CODESPACE_NAME
          else
            echo "Codespace is already running."
          fi